### PR TITLE
Altering input hit list name to master algorithm.

### PR DESCRIPTION
**Pull request by StevenGreen1**
This PR is needed in order to allow the PreProcessorAlgorithm to cut on the number of hits in an event.  No performance change beyond vetoing certain events with large numbers of hits, cut configurable via xml, default limit std::numeric_limits<int>::max(), is expected.

### CODE REVIEW

**Comment by loressa** [comment]
Hi,

Agreed with John, providing they have been tested and not breaking anything, there is nothing else to check in this PR.

Best,
Lorena

**Comment by StevenGreen1** [comment]
The changes in this PR have been applied to dunetpc (PandoraSettings_Master_DUNEFD.xml & PandoraSettings_Master_ProtoDUNE.xml 

Cheers,
Steve

**Comment by StevenGreen1** [comment]
I've merged this change for the ProtoDUNE and DUNEFD xml settings files into the master to reflect what is now in LArSoft.  MicroBooNE, SBND and ICARUS changes are still needed.

**Comment by PandoraPFA** [comment]
These changes have all been merged manually long ago.

**Pull request closed without merging**
