### PR TITLE
Edepsim neutrino hypothesis xml

### PR DESCRIPTION
**Pull request by afm1g15**

### CODE REVIEW

**Comment by jback08** [comment]
Before we add this, I would like to understand if this is significantly different to [PandoraSettings_EDepReco.xml](https://github.com/PandoraPFA/LArReco/blob/feature/edep-reco/settings/PandoraSettings_EDepReco.xml#L27) which calls the MicroBooNE neutrino algorithms defined in [PandoraSettings_Neutrino_MicroBooNE.xml](https://github.com/PandoraPFA/LArReco/blob/feature/edep-reco/settings/PandoraSettings_Neutrino_MicroBooNE.xml)?

**Comment by AndyChappell** [comment]
> Before we add this...

Noted, I'll hold off merging pending an update.

**Comment by afm1g15** [comment]
@AndyChappell We're on it, hopefully should reach a conclusion by today

**Comment by afm1g15** [comment]
Updated this to what I agreed with @jback08

**Pull request merged**
