### PR TITLE
Fix coverity stripping in untar.

### PR DESCRIPTION
**Pull request by PandoraPFA**

### CODE REVIEW

**Comment by StevenGreen1** [comment]
Happy for this to be merged. 
Cheers
Steve

**Comment by PandoraPFA** [comment]
Should we merge this now? We should also check and tag LArReco so that it's consistent with the tags of LArContent.

**Comment by StevenGreen1** [comment]
Yeah we should put this in.  I might have time to get around to it this week, but if not will aim for. next week (although if anyone else is keen and wants to just do it, then please do).  Cheers.

**Comment by StevenGreen1** [comment]
Merged  via command line.

**Pull request closed without merging**
