### PR TITLE
Remove erroneous ZeroMode in first cluster characterisation

### PR DESCRIPTION
**Pull request by henrylay97**
Keeps the xml current with the version in sbndcode.

### CODE REVIEW

**Comment by johnmarshall80** [comment]
Hi @henrylay97 - Good spot. This looks like it can go straight in to LArReco (will leave it a little while to give others the chance to comment too). Can obviously liaise with @etyley, @absolution1, etc. about getting this fix into sbndcode. Thanks.

**Comment by henrylay97** [comment]
Thanks @johnmarshall80 sounds good! The sbndcode PR has been merged today.

**Comment by AndyChappell** [comment]
Looks fine to me too.

**Comment by etyley** [comment]
Henry has been liaising with Dom and me offline, he has checked that there are no adverse effects on the output by making this change so all looks good to me

**Pull request merged**
